from enum import Enum
from typing import List, Tuple, Dict, Any, Optional
from pydantic import BaseModel, Field, field_validator


class ModalityEnum(str, Enum):
    TEXT = "text"
    IMAGE = "image"
    AUDIO = "audio"
    VIDEO = "video"


class VerdictEnum(str, Enum):
    DECLARED_AI = "declared_ai"
    LIKELY_AUTHENTIC = "likely_authentic"
    UNCERTAIN = "uncertain"
    LIKELY_MANIPULATED = "likely_manipulated"


class Signal(BaseModel):
    name: str = Field(..., description="Machine identifier for the signal")
    human: str = Field(..., description="Plain-English sentence describing the finding")
    value: Any = Field(..., description="Extracted metric or categorical value")
    weight: float = Field(..., ge=0.0, le=1.0, description="Importance weight of this signal")
    where: Optional[Any] = Field(None, description="Region of image, seconds range, line number, or spatial bbox")


class Reliability(BaseModel):
    ood_flags: List[str] = Field(default_factory=list, description="Out-of-distribution or failure condition flags")
    band: float = Field(default=0.0, ge=0.0, le=1.0, description="Confidence interval widening factor due to reliability risks")
    note: Optional[str] = Field(None, description="Human readable reliability note")


class Evidence(BaseModel):
    modality: ModalityEnum
    verdict: VerdictEnum
    score: float = Field(..., ge=0.0, le=1.0, description="Calibrated float score 0.0 to 1.0 (higher = more suspicious)")
    confidence: Tuple[float, float] = Field(..., description="Confidence interval tuple (low, high)")
    signals: List[Signal] = Field(default_factory=list, description="List of observed signals")
    reliability: Reliability = Field(default_factory=Reliability, description="Reliability assessment and OOD gates")
    provenance: Dict[str, Any] = Field(default_factory=dict, description="Metadata / header provenance tags")
    findings: Optional[Any] = Field(None, description="Optional extra details or breakdown")
    explanation: str = Field(default="", description="Plain English narrative generated by shared explainer")

    @field_validator("confidence")
    @classmethod
    def validate_confidence(cls, v: Tuple[float, float]) -> Tuple[float, float]:
        low, high = v
        low_clamped = max(0.0, min(1.0, round(low, 3)))
        high_clamped = max(0.0, min(1.0, round(high, 3)))
        if low_clamped > high_clamped:
            low_clamped, high_clamped = high_clamped, low_clamped
        return (low_clamped, high_clamped)


def derive_verdict_and_confidence(
    score: float,
    reliability: Reliability,
    provenance: Dict[str, Any]
) -> Tuple[VerdictEnum, Tuple[float, float]]:
    """
    Core business logic enforcing Truth Lens non-negotiable rules:
    1. Provenance metadata declared_ai -> DECLARED_AI
    2. OOD flags present -> UNCERTAIN (reliability gate widens band)
    3. Score < 0.35 -> LIKELY_AUTHENTIC ("no evidence of manipulation")
    4. Score > 0.65 -> LIKELY_MANIPULATED
    5. Score 0.35-0.65 -> UNCERTAIN
    """
    # Check declared AI provenance
    is_declared = provenance.get("declared_ai", False) or provenance.get("is_synthetic_metadata", False)
    if is_declared:
        verdict = VerdictEnum.DECLARED_AI
    elif len(reliability.ood_flags) > 0:
        verdict = VerdictEnum.UNCERTAIN
    elif score < 0.35:
        verdict = VerdictEnum.LIKELY_AUTHENTIC
    elif score > 0.65:
        verdict = VerdictEnum.LIKELY_MANIPULATED
    else:
        verdict = VerdictEnum.UNCERTAIN

    # Calculate confidence interval: base margin ±0.05 plus reliability widening band
    base_margin = 0.05
    widening = reliability.band
    total_delta = base_margin + widening
    
    low = max(0.0, score - total_delta)
    high = min(1.0, score + total_delta)
    
    return verdict, (round(low, 3), round(high, 3))
